# Generated by Django 3.2.6 on 2021-09-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanxuat', '0003_sanpham_congdoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanCongDoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CongDoan', models.ManyToManyField(to='sanxuat.CongDoan')),
                ('TenSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.sanpham')),
            ],
        ),
    ]
