# Generated by Django 3.2.8 on 2022-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='luongngaynhanvien',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='soluonglam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
    ]
