# Generated by Django 3.2.8 on 2021-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0001_initial'),
        ('QuyTrinhSanXuat', '0002_alter_gan_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gan',
            name='NhanVien',
            field=models.ManyToManyField(blank=True, null=True, to='sanxuat.NhanVien'),
        ),
    ]
