# Generated by Django 3.2.8 on 2021-11-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0002_auto_20211103_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gancongdoan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gancongdoan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='soluonglam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soluonglam',
            name='updated_at',
        ),
    ]
