# Generated by Django 3.2.7 on 2021-09-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_remove_sanpham_congdoan'),
        ('QuyTrinhSanXuat', '0003_auto_20210920_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gan',
            name='NhanVien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.nhanvien'),
        ),
    ]
