# Generated by Django 3.2.7 on 2021-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0004_gan_nhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancongdoan',
            name='NhipSanXuat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gancongdoan',
            name='TongNhanVien',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gancongdoan',
            name='TongThoiGian',
            field=models.IntegerField(null=True),
        ),
    ]
