# Generated by Django 3.2.8 on 2021-11-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_auto_20211103_2151'),
        ('QuyTrinhSanXuat', '0004_auto_20211103_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoLuongMoiGio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TamDenChinGio', models.IntegerField()),
                ('ChinDenMuoiGio', models.IntegerField()),
                ('MuoiDenMuoiMot', models.IntegerField()),
                ('MuoiMotDenMuoiHai', models.IntegerField()),
                ('MotDenHai', models.IntegerField()),
                ('HaiDenBa', models.IntegerField()),
                ('BaDenBon', models.IntegerField()),
                ('BonDenNam', models.IntegerField()),
                ('ThemGio', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('NhanVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.nhanvien')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.sanpham')),
            ],
        ),
    ]
