# Generated by Django 3.2.8 on 2021-11-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0005_soluongmoigio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluongmoigio',
            name='BaDenBon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='BonDenNam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='ChinDenMuoiGio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='HaiDenBa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MotDenHai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MuoiDenMuoiMot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MuoiMotDenMuoiHai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='TamDenChinGio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='ThemGio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
