# Generated by Django 3.2.7 on 2021-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0005_auto_20210920_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancongdoan',
            name='SaiSoChoPhep',
            field=models.FloatField(default=0),
        ),
    ]
