# Generated by Django 3.2.8 on 2021-11-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_auto_20211103_2151'),
        ('QuyTrinhSanXuat', '0006_auto_20211103_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='soluongmoigio',
            name='CongDoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.congdoan'),
        ),
    ]
