# Generated by Django 3.2.7 on 2021-09-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_remove_sanpham_congdoan'),
        ('QuyTrinhSanXuat', '0006_gancongdoan_saisochophep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gan',
            name='NhanVien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.nhanvien'),
        ),
    ]
