# Generated by Django 3.2.7 on 2021-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0007_alter_gan_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancongdoan',
            name='NhipSanXuat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gancongdoan',
            name='SaiSoChoPhep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gancongdoan',
            name='TongNhanVien',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gancongdoan',
            name='TongThoiGian',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
