# Generated by Django 3.2.8 on 2021-11-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_auto_20211103_2151'),
        ('QuyTrinhSanXuat', '0007_soluongmoigio_congdoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuongNgayNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LuongNgayHomTruoc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('LuongNgayHomNay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('LuongThang', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('NhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.nhanvien')),
            ],
        ),
    ]
