# Generated by Django 3.2.7 on 2021-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0008_auto_20210920_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='gan',
            name='TongThoiGianCuaNhanVien',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
