# Generated by Django 3.2.8 on 2021-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0008_luongngaynhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luongngaynhanvien',
            name='LuongNgayHomNay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='luongngaynhanvien',
            name='LuongNgayHomTruoc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='luongngaynhanvien',
            name='LuongThang',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
