# Generated by Django 3.2.7 on 2021-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0009_gan_tongthoigiancuanhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gan',
            name='TongThoiGianCuaNhanVien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
