# Generated by Django 3.2.8 on 2021-11-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0009_auto_20211105_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luongngaynhanvien',
            options={'verbose_name_plural': 'Lương Ngày Của Nhân Viên'},
        ),
        migrations.AlterModelOptions(
            name='soluongmoigio',
            options={'verbose_name_plural': 'Số Lượng Làm Mỗi Giờ'},
        ),
    ]
