# Generated by Django 3.2.8 on 2021-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0010_auto_20211110_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluongmoigio',
            name='BaDenBon',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='BonDenNam',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='ChinDenMuoiGio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='HaiDenBa',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MotDenHai',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MuoiDenMuoiMot',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='MuoiMotDenMuoiHai',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='TamDenChinGio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='soluongmoigio',
            name='ThemGio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
