# Generated by Django 3.2.8 on 2021-10-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_remove_sanpham_congdoan'),
        ('QuyTrinhSanXuat', '0010_alter_gan_tongthoigiancuanhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancongdoan',
            name='SanLuong1Gio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gancongdoan',
            name='SoLuong1Ngay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gancongdoan',
            name='SoLuongSanPham',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gancongdoan',
            name='SoNgayHoanThanh',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SoLuongLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TongThoiGianCuaNhanVien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CongDoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuyTrinhSanXuat.gancongdoan')),
                ('GiaCongDoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.congdoan')),
                ('NhanVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.nhanvien')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.sanpham')),
            ],
        ),
    ]
