# Generated by Django 3.2.8 on 2021-11-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0005_sanpham_hoan_tat'),
        ('QuyTrinhSanXuat', '0011_auto_20211110_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancongdoan',
            name='TenSanPham',
            field=models.ForeignKey(limit_choices_to={'hoan_tat': False}, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.sanpham'),
        ),
    ]
