# Generated by Django 3.2.8 on 2021-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_remove_sanpham_congdoan'),
        ('QuyTrinhSanXuat', '0011_auto_20211021_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='soluonglam',
            name='KichCauDeTangLuong',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='LuongNgay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='LuongNgayToiThieu',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='SoLuongDatTiepTheo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='SoLuongToiThieu',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='soluonglam',
            name='CongDoan',
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='CongDoan',
            field=models.ManyToManyField(to='sanxuat.CongDoan'),
        ),
        migrations.AlterField(
            model_name='soluonglam',
            name='GiaCongDoan',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
