# Generated by Django 3.2.8 on 2021-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0012_auto_20211023_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancongdoan',
            name='SoLuongLam',
            field=models.ManyToManyField(to='QuyTrinhSanXuat.SoLuongLam'),
        ),
    ]
