# Generated by Django 3.2.8 on 2021-10-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0013_gancongdoan_soluonglam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gancongdoan',
            name='SoLuongLam',
        ),
    ]
