# Generated by Django 3.2.8 on 2021-10-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0014_remove_gancongdoan_soluonglam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluonglam',
            name='CongDoan',
        ),
        migrations.AddField(
            model_name='soluonglam',
            name='GanCongDoan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuyTrinhSanXuat.gancongdoan'),
        ),
    ]
