# Generated by Django 3.2.8 on 2021-10-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuyTrinhSanXuat', '0015_auto_20211024_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluonglam',
            name='GanCongDoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuyTrinhSanXuat.gancongdoan'),
        ),
    ]
