# Generated by Django 3.2.6 on 2021-09-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bactho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbactho', models.TextField(verbose_name='Tên Bậc Thợ')),
                ('dongia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn Giá')),
                ('LuongTamTinh', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Lương Tạm Tính')),
            ],
            options={
                'verbose_name_plural': 'Bậc Thợ',
            },
        ),
        migrations.CreateModel(
            name='phongban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenphongban', models.TextField(verbose_name='Tên Phòng Ban')),
                ('diengiai', models.TextField(verbose_name='Diễn Giải')),
            ],
            options={
                'verbose_name_plural': 'Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='thietbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenthietbi', models.TextField(verbose_name='Tên Thiết Bị')),
                ('soluong', models.IntegerField(verbose_name='Số Lượng')),
            ],
            options={
                'verbose_name_plural': 'Thiết Bị',
            },
        ),
        migrations.CreateModel(
            name='chucvu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenchucvu', models.TextField(verbose_name='Tên Chức Vụ')),
                ('tenphongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauhinh.phongban', verbose_name='Tên Phòng Ban')),
            ],
            options={
                'verbose_name_plural': 'Chức Vụ',
            },
        ),
    ]
