# Generated by Django 3.2.8 on 2022-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauhinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phantramthuong', models.DecimalField(decimal_places=2, default=1.2, max_digits=10, verbose_name='Phần trăm thưởng')),
            ],
        ),
    ]
