# Generated by Django 3.2.8 on 2021-10-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cauhinh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChuyen', models.TextField(verbose_name='Tên Chuyền')),
            ],
            options={
                'verbose_name_plural': 'Chuyền',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaSanPham', models.TextField(verbose_name='Mã Sản Phẩm')),
                ('TenSanPham', models.TextField(verbose_name='Tên Sản Phẩm')),
                ('SoLuong', models.IntegerField(verbose_name='Số Lượng')),
                ('DonGia', models.FloatField(verbose_name='Đơn Giá')),
                ('NgayDongBo', models.DateField(verbose_name='Ngày Đồng Bộ')),
                ('NgayGiaoHang', models.DateField(verbose_name='Ngày Giao Hàng')),
                ('DienGiai', models.TextField(verbose_name='Ghi Chú')),
                ('ChuyenThucHien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.chuyen', verbose_name='Giao Việc Cho')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhanVien', models.CharField(max_length=255, null=True, verbose_name='Tên Nhân Viên')),
                ('SoDienThoai', models.IntegerField(blank=True, null=True, verbose_name='Số Điện Thoại')),
                ('NgaySinh', models.DateField(blank=True, null=True, verbose_name='Ngày Sinh')),
                ('DiaChi', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Đại Chỉ')),
                ('TinhTrang', models.CharField(choices=[('BT', 'BÌNH THƯỜNG'), ('TN', 'TẠM NGHỈ'), ('NV', 'NGHỈ VIỆC')], max_length=20)),
                ('BacTho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cauhinh.bactho', verbose_name='Bậc Thợ')),
                ('ChucDanh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cauhinh.chucvu', verbose_name='Chức Danh')),
                ('MayUT1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cauhinh.thietbi', verbose_name='Ưu Tiên 1')),
                ('TenChuyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanxuat.chuyen', verbose_name='Thuộc Chuyền')),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='CongDoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCongDoan', models.TextField(verbose_name='Tên Công Đoạn')),
                ('NhomCongDoan', models.CharField(choices=[('CB', 'CHUẨN BỊ'), ('SX', 'SẢN XUẤT'), ('HT', 'HOÀN THÀNH')], default=2, max_length=2, verbose_name='Nhóm Công Đoạn')),
                ('ThoiGianHoanThanh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thời Gian Hoàn Thành')),
                ('DonGia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Đơn Giá')),
                ('BacTho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauhinh.bactho', verbose_name='Bậc Thợ')),
                ('ThietBi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauhinh.thietbi', verbose_name='Thiết Bị')),
            ],
            options={
                'verbose_name_plural': 'Công Đoạn',
            },
        ),
    ]
