# Generated by Django 3.2.8 on 2022-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='Ho',
            field=models.CharField(max_length=255, null=True, verbose_name='Họ Tên Đệm'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Ten',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên'),
        ),
    ]
