# Generated by Django 3.2.6 on 2021-09-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaSanPham', models.TextField(verbose_name='Mã Sản Phẩm')),
                ('TenSanPham', models.TextField(verbose_name='Tên Sản Phẩm')),
                ('SoLuong', models.IntegerField(verbose_name='Số Lượng')),
                ('DonGia', models.FloatField(verbose_name='Đơn Giá')),
                ('NgayDongBo', models.DateField(verbose_name='Ngày Đồng Bộ')),
                ('NgayGiaoHang', models.DateField(verbose_name='Ngày Giao Hàng')),
                ('DienGiai', models.TextField(verbose_name='Ghi Chú')),
                ('ChuyenThucHien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanxuat.chuyen', verbose_name='Giao Việc Cho')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm',
            },
        ),
    ]
