# Generated by Django 3.2.8 on 2021-11-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0002_auto_20211103_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='updated_at',
        ),
    ]
