# Generated by Django 3.2.6 on 2021-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0002_sanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='CongDoan',
            field=models.ManyToManyField(to='sanxuat.CongDoan'),
        ),
    ]
