# Generated by Django 3.2.8 on 2022-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0002_auto_20220111_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='SoDienThoai',
            field=models.CharField(default='0', max_length=255, verbose_name='Số Điện Thoại'),
        ),
    ]
