# Generated by Django 3.2.8 on 2022-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0003_alter_nhanvien_sodienthoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='SoDienThoai',
            field=models.CharField(max_length=255, verbose_name='Số Điện Thoại'),
        ),
    ]
