# Generated by Django 3.2.8 on 2021-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0004_auto_20211103_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hoan_tat',
            field=models.BooleanField(default=False, verbose_name='Hoàn tất'),
        ),
    ]
