# Generated by Django 3.2.8 on 2021-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0005_sanpham_hoan_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='TinhTrang',
            field=models.CharField(choices=[('BT', 'BÌNH THƯỜNG'), ('TN', 'TẠM NGHỈ'), ('NV', 'NGHỈ VIỆC')], max_length=20, null=True),
        ),
    ]
