# Generated by Django 3.2.8 on 2021-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanxuat', '0007_alter_nhanvien_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='updated_at',
        ),
    ]
